services:
  - type: web
    name: elaina-bot
    env: node
    plan: free
    buildCommand: |
      npm install
    startCommand: |
      node index.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SESSION_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
